remap f5 crash to f9
Llennpie/Saturn pull request #33
Opened 2023-08-17 17:21 UTC by Dominicentek

remap f5 crash button to f9 so that people dont crash saturn trying to toggle timeline using f6
suggested by sm64mods

2023-08-20 05:49 UTC, integerbang requested changes

2023-08-20 05:49 UTC, integerbang commented on src/saturn/saturn_projectfile.cpp
> +ushort get_int16(char* data, int* offset) {
`ushort` should be either defined or changed to `u16` or `uint16_t`.

2023-08-20 05:49 UTC, integerbang commented on src/saturn/saturn_projectfile.cpp
> +    ushort value = (get_int8(data, offset) << 8) | get_int8(data, offset);
Same issue as line [100](https://github.com/Llennpie/Saturn/blob/f987112d8bf0845917a5dc8266ab123e64f72400/src/saturn/saturn_projectfile.cpp#L100).

2023-08-20 05:49 UTC, integerbang commented on src/saturn/saturn_projectfile.cpp
> +void put_int16(char* data, int* offset, ushort value) {
Same issue as lines [100](https://github.com/Llennpie/Saturn/blob/f987112d8bf0845917a5dc8266ab123e64f72400/src/saturn/saturn_projectfile.cpp#L100) and [101](https://github.com/Llennpie/Saturn/blob/f987112d8bf0845917a5dc8266ab123e64f72400/src/saturn/saturn_projectfile.cpp#L101).

2023-08-20 05:49 UTC, integerbang commented on src/saturn/saturn_projectfile.cpp
> +            ushort flags = get_int16(data, &pointer);
Same issue as lines [100](https://github.com/Llennpie/Saturn/blob/f987112d8bf0845917a5dc8266ab123e64f72400/src/saturn/saturn_projectfile.cpp#L100), [101](https://github.com/Llennpie/Saturn/blob/f987112d8bf0845917a5dc8266ab123e64f72400/src/saturn/saturn_projectfile.cpp#L101), and [138](https://github.com/Llennpie/Saturn/blob/f987112d8bf0845917a5dc8266ab123e64f72400/src/saturn/saturn_projectfile.cpp#L138).

2023-08-25 23:33 UTC, integerbang commented
@Dominicentek, sorry for not being around to review your changes quickly, by the way.

I'm a bit busy with some other stuff. Once I have time to review your changes, I'll let you know if they're all okay for merging or if there are still some improvements that could be made. 👍

2023-08-25 23:37 UTC, integerbang commented
I should mention that it might be better to split some of your changes into a separate pull request since it seems like there's a lot of new functionality to look over.

Some things not wholly related to the new project file format could be split into their own pull request, while most of the stuff involving corrections or simple fixes could be merged or rebased with the other commits.

2023-08-25 23:39 UTC, Dominicentek commented
Ah okay, I understand

2023-08-28 01:16 UTC, integerbang approved these changes
Waiting for @Llennpie to merge or review.

2023-08-29 02:45 UTC, merged